In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

In [2]:
df = pd.read_csv('customer_churn_dataset-testing-master.csv')

print('Dataset Shape:')
print(df.shape)

print('\nFirst 5 rows:')
df.head()

Dataset Shape:
(64374, 12)

First 5 rows:

   CustomerID  Age  Gender  ...  Total Spend  Last Interaction  Churn
0           1   22  Female  ...          598                 9      1
1           2   41  Female  ...          584                20      0
2           3   47    Male  ...          757                21      0
3           4   35    Male  ...          232                18      0
4           5   53  Female  ...          533                18      0

[5 rows x 12 columns]

## Cleaning Data

In [3]:
print('\nMissing values:')
print(df.isnull().sum())

print('\nTarget distribution:')
print(df['Churn'].value_counts(normalize=True))

Missing values:
CustomerID           0
Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64

Target distribution:
Churn
0    0.526315
1    0.473685
Name: proportion, dtype: float64

In [9]:
X = df.drop('Churn', axis=1)
y = df['Churn']

lbe_gender = LabelEncoder()
lbe_gender.fit(X['Gender'].drop_duplicates())
X['Gender'] = lbe_gender.transform(X['Gender'])

lbe_subscriptiontype = LabelEncoder()
lbe_subscriptiontype.fit(X['Subscription Type'].drop_duplicates())
X['Subscription Type'] = lbe_subscriptiontype.transform(X['Subscription Type'])


lbe_Contract = LabelEncoder()
lbe_Contract.fit(X['Contract Length'].drop_duplicates())

X['Contract Length'] = lbe_Contract.transform(X['Contract Length'])

X.head()

   CustomerID  Age  Gender  ...  Contract Length  Total Spend  Last Interaction
0           1   22       0  ...                1          598                 9
1           2   41       0  ...                1          584                20
2           3   47       1  ...                0          757                21
3           4   35       1  ...                2          232                18
4           5   53       0  ...                0          533                18

[5 rows x 11 columns]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape)

print(X_test.shape)

(51499, 11)
(12875, 11)

In [11]:
model = RandomForestClassifier(n_estimators=200)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

In [ ]:
print(accuracy_score(y_test, y_pred))

0.9980582524271845